const newProductArray = [
    {
        pid: 4,
        pname: 'OVE LINEN SOFA',
        pdesc: `부드러운 린넨 패브릭과 낮고 넓은 실루엣으로 편안한 휴식을 완성하는 3인용 소파`,
        price: 1280000,
        pdiscount: 0.15,
        pthumbFileName: 'new1.jpg',
    },
    {
        pid: 5,
        pname: 'MONO ARC CHAIR',
        pdesc: `부드러운 곡선형 구조와 원형 프레임이 조화로운 아치 체어`,
        price: 420000,
        pdiscount: 0,
        pthumbFileName: 'new2.jpg',
    },
    {
        pid: 6,
        pname: 'ELLW WALNUT TABLE',
        pdesc: `우아한 원형 상판과 따뜻한 월넛 컬러가 살아있는 원목 테이블`,
        price: 890000,
        pdiscount: 0.1,
        pthumbFileName: 'new3.jpg',
    },
    {
        pid: 7,
        pname: 'VEIL SIDE TABLE',
        pdesc: `소파 옆이나 침실 구석에 자연스럽게 어우러지는 심플 사이드 테이블`,
        price: 260000,
        pdiscount: 0,
        pthumbFileName: 'new4.jpg',
    },
    {
        pid: 8,
        pname: 'NOTE OAK BED',
        pdesc: `통일감 있는 오크 우드와 부드러운 헤드보드 디자인으로 침실을 고급스럽게 연출`,
        price: 1050000,
        pdiscount: 0.2,
        pthumbFileName: 'new5.jpg',
    },
    {
        pid: 9,
        pname: 'RIB 4-TIER SHELF',
        pdesc: `책과 소품을 정리하기 좋은 수납형 오픈 선반으로 공간을 깔끔하게 완성`,
        price: 580000,
        pdiscount: 0,
        pthumbFileName: 'new6.jpg',
    },
    {
        pid: 10,
        pname: 'ARCO FABRIC BENCH',
        pdesc: `부드러운 패브릭 소재와 둥근 라인으로 조화로운 분위기를 더하는 벤치`,
        price: 370000,
        pdiscount: 0,
        pthumbFileName: 'new7.jpg',
    },
    {
        pid: 11,
        pname: 'CLAIRE GLASS TABLE',
        pdesc: `유리 상판과 가벼운 구조가 공간을 더 넓고 세련되게 보이게 하는 테이블`,
        price: 490000,
        pdiscount: 0.12,
        pthumbFileName: 'new8.jpg',
    },
    {
        pid: 12,
        pname: 'LOWOID WIDE CABINET',
        pdesc: `넓은 수납 공간과 미니멀한 디자인으로 거실과 침실에 모두 잘 어울리는 캐비닛`,
        price: 980000,
        pdiscount: 0,
        pthumbFileName: 'new9.jpg',
    },
    {
        pid: 13,
        pname: 'SAGE RECLINING CHAIR',
        pdesc: `가볍고 편안한 좌석감과 세련된 라인이 돋보이는 안락의자`,
        price: 690000,
        pdiscount: 0.18,
        pthumbFileName: 'new10.jpg',
    },
    {
        pid: 14,
        pname: 'ORBIS ROUND MIRROR',
        pdesc: `둥근 형태와 따뜻한 톤의 프레임이 벽면을 정리하고 고급스러운 포인트를 더해줍니다.`,
        price: 310000,
        pdiscount: 0,
        pthumbFileName: 'new11.jpg',
    },
    {
        pid: 15,
        pname: 'LUMEN 6-DRAWER CHEST',
        pdesc: `다용도 수납과 세련된 우드 톤이 조화를 이루는 6단 서랍장`,
        price: 760000,
        pdiscount: 0,
        pthumbFileName: 'new12.jpg',
    },
];