const product = [
    {
        pid: 0,
        pname: 'AERA Bed Frame',
        pdesc: `낮고 넓은 헤드보드와 자연스러운 우드 질감이 돋보이는 침대 프레임. 침실에 차분하고 안정적인 분위기를 더해줍니다.`,
        price: 1820000,
        pdiscount: 0.2,
        priceDiscount: 1456000,
        plikes: 412,
        pthumbFileName: 'sale1.jpg',
    },
    {
        pid: 1,
        pname: 'SENA Side Table',
        pdesc: `둥근 상판과 슬림한 다리 구조로 완성한 컴팩트한 사이드 테이블. 침대 옆이나 소파 주변에 가볍게 배치하기 좋습니다.`,
        price: 488000,
        pdiscount: 0.2,
        priceDiscount: 390000,
        plikes: 276,
        pthumbFileName: 'sale2.jpg',
    },
    {
        pid: 2,
        pname: 'RIVA Bookshelf',
        pdesc: `비대칭 선반 구조와 절제된 프레임이 특징인 오픈형 책장. 책과 오브제를 함께 배치해 공간에 개성을 더할 수 있습니다.`,
        price: 975000,
        pdiscount: 0.2,
        priceDiscount: 780000,
        plikes: 354,
        pthumbFileName: 'sale3.jpg',
    },
    {
        pid: 3,
        pname: 'ORIN Bench',
        pdesc: `간결한 직선 실루엣과 부드러운 패브릭 쿠션이 조화를 이루는 벤치. 현관이나 침실, 다이닝 공간에서 다양하게 활용할 수 있습니다.`,
        price: 675000,
        pdiscount: 0.2,
        priceDiscount: 540000,
        plikes: 198,
        pthumbFileName: 'sale4.jpg',
    },
];